### PR TITLE
Use official API to check for Classic or Retail

### PR DESCRIPTION
**Pull request by wolfcon**

### CODE REVIEW

**Comment by doadin** [comment]
Thanks for this also, libbagutils-1-0, is public domain so I have started a new repo https://github.com/doadin/LibBagUtils-1.0 to get it up to date/working for classic and retail. Import on that hasn't finished yet.

**Comment by doadin** [comment]
With the new libbagutils I get a very close to working version for clasic and retail. Both have some minor issues though. Currently waiting to get approval on curse I sent them a screenshot of mike giving the ok and added a support member to that DM hopefully one of those will get it approved soon.

**Comment by doadin** [comment]
I actually now have owner on the original so we are good to go now! Thanks again for you help! Theres still like one issue on each game version I gotta work out but not too bad so far.

**Comment by wolfcon** [comment]
nice~. He don't reply me. Just because I have no repo I guess. I send him PM a long time ago.
Anyway. Update is live

**Pull request merged**
